### ISSUE TITLE
Error with Version 3.0.8

### ISSUE THREAD

**Issue by kcsahoo** [s-panferov/awesome-typescript-loader#382]
I am using V 3.0.8 with Typescript 2.1.1
I am getting error:
Module Build Failed : Error: Final loader didn't return a Buffer or String

The same error throws with any V 3 and Typescript 2.1,x

It works with V 2.2.4 and Typescript 2.0.10

ts-loader does not have problem with Typescript 2.2.1

Can this be fixed please.
Note - I have installed all loaders advised in different forums.

**Comment by jonrimmer** [comment]
Is every loader name in your webpack.config.js suffixed with "-loader"? This is a requirement in Webpack 2, and can cause the error you're getting. E.g.

```js
  loaders: ['ng-annotate', 'awesome-typescript']
```

Is no longer valid. It must be:

```js
  loaders: ['ng-annotate-loader', 'awesome-typescript-loader']
```

**Comment by RafaelSalguero** [comment]
I have the same problem, the loaders names are correct on my project

**Comment by giniedp** [comment]
this is what i am getting during compilation since version 3.0.8

```
[at-loader]: Child process failed to process the request:  TypeError: Cannot read property 'path' of undefined
    at /Users/alex/repositories/gebeco/gbc3/node_modules/typescript/lib/typescript.js:43764:45
    at Map.forEach (native)
    at createResolver (/Users/alex/repositories/gebeco/gbc3/node_modules/typescript/lib/typescript.js:43759:49)
    at Object.createTypeChecker (/Users/alex/repositories/gebeco/gbc3/node_modules/typescript/lib/typescript.js:24712:28)
    at Object.getTypeChecker (/Users/alex/repositories/gebeco/gbc3/node_modules/typescript/lib/typescript.js:64254:79)
    at synchronizeHostData (/Users/alex/repositories/gebeco/gbc3/node_modules/typescript/lib/typescript.js:81190:21)
    at Object.getProgram (/Users/alex/repositories/gebeco/gbc3/node_modules/typescript/lib/typescript.js:81272:13)
    at processInit (/Users/alex/repositories/gebeco/gbc3/node_modules/awesome-typescript-loader/src/checker/runtime.ts:264:33)
    at /Users/alex/repositories/gebeco/gbc3/node_modules/awesome-typescript-loader/src/checker/runtime.ts:460:21
    at Object.send (/Users/alex/repositories/gebeco/gbc3/node_modules/awesome-typescript-loader/src/checker/runtime.ts:27:21)
    at Checker.req (/Users/alex/repositories/gebeco/gbc3/node_modules/awesome-typescript-loader/src/checker/checker.ts:101:21)
    at new Checker (/Users/alex/repositories/gebeco/gbc3/node_modules/awesome-typescript-loader/src/checker/checker.ts:80:14)
    at Object.ensureInstance (/Users/alex/repositories/gebeco/gbc3/node_modules/awesome-typescript-loader/src/instance.ts:129:21)
    at compiler (/Users/alex/repositories/gebeco/gbc3/node_modules/awesome-typescript-loader/src/index.ts:45:22)
    at Object.loader (/Users/alex/repositories/gebeco/gbc3/node_modules/awesome-typescript-loader/src/index.ts:14:18)
    at LOADER_EXECUTION (/Users/alex/repositories/gebeco/gbc3/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
```

**Comment by vincentw56** [comment]
Same problem here. I double-checked my loader names, Now I cannot get it to build.

**Comment by RafaelSalguero** [comment]
I fixed my problem by having the same case on the `require`s and on the file and folder names. This is problematic since my enviroment is case-insensitive

**Comment by vincentw56** [comment]
I am using Windows so case shouldn't matter. It has never been an issue before. This has been working fine for me until just today. I switched to ts-loader and everything works fine. It is slower, but at least I can do my work.

**Comment by szahn** [comment]
Same problem. Using Webpack 2.2.1, Typescript 2.1.5 awesome-typescript-loader 3.0.8.

```
ERROR in ./app/upload/services/fileUploadQueue.ts
Module build failed: Error: Final loader didn't return a Buffer or String
    at C:\Repo\App\node_modules\webpack\lib\NormalModule.js:149:64
    at C:\Repo\App\node_modules\loader-runner\lib\LoaderRunner.js:370:3
    at iterateNormalLoaders (C:\Repo\App\node_modules\loader-runner\lib\LoaderRunner.js:211:10)
    at iterateNormalLoaders (C:\Repo\App\node_modules\loader-runner\lib\LoaderRunner.js:218:10)
    at C:\Repo\App\node_modules\loader-runner\lib\LoaderRunner.js:233:3
    at context.callback (C:\Repo\App\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Repo\App\node_modules\awesome-typescript-loader\src\index.ts:106:13
 @ ./app/upload/uploadModule.ts 2:22-59
 @ multi ./app/security/securityModule.ts ./app/common/commonModule.ts ./app/dashboard/dashboardModule.ts ./app/proofing/proofingModule.ts .
/app/reports/reportsModule.ts ./app/upload/uploadModule.ts ./app/admin/adminModule.ts ./app/appModule.ts ./generated/templates.js
```

**Comment by vincentw56** [comment]
Looks like this is fixed in version 3.1.2.

**Comment by kcsahoo** [comment]
No
I am using Awesome 3.1.2 and Typescript 2.2.1
I am getting the following error:
Module build failed:Error:Final loader didn't return a Buffer or String
I am using Windows.

Everything works with combination:
Awesome 2.2.4 and Typescript 2.1.1/2.0.10

With Typescript 2.2.1 and ts-loader, no problem.

**Comment by kcsahoo** [comment]
I am using webpack 2.2.1 if it helps to identify the issue

**Comment by kcsahoo** [comment]
Issue resolved with Awesome 3.1.2 and Typescript 2.2.1.
I had duplicate tsconfig.json with non-matching entries.
Removed duplicate and the error disappeared.

**Comment by kcsahoo** [comment]
No I am wrong.
It still does not work and has the same error.
Only works with ATL V2.2.4 and Typescript 2.1.1/2.0.10

**Comment by vincentw56** [comment]
I am running Webpack 2.2.1, Typescript 2.2.1, and Awesome Typescript Loader 3.1.2 with no issues. Try deleting your .awcache folder. I've found sometimes that fixes some issues with Awesome Typescript Loader.

**Comment by kcsahoo** [comment]
Where is .awcache folder?
I cannot find in node_modules folder.

**Comment by vincentw56** [comment]
It is not in the node_modules folder. It should be in the root or same folder level as the node_modules level. That is how it is on all my projects on Windows.

![image](https://cloud.githubusercontent.com/assets/1850511/23913848/8f39714c-08ba-11e7-8d6c-9a8ce3772372.png)

**Comment by giniedp** [comment]
i dont use the cache, and still experience the issue. Thus i'm stuck at version 3.0.7 as my last stable version

typescript: 2.2.1
webpack: 2.2.1

**Comment by kcsahoo** [comment]
I also do not use cache nor have .awcache directory.
The strange thing is ts-loader works fine with Typescript 2.2.1.
In ATL, everything works with V 2.2.4 and Typescript 2.1.1
Once Typescript version is chosen as 2.1.4 or above, errors pop up from ATL.
There were breaking changes in TS 2.1.4.
ATL has not been checked for TS versions 2.1.4 and above.
Small examples work but a reasonably big application breaks.

**Comment by kcsahoo** [comment]
Does not work with ATL 3.0.7 for me.
Only 2.2.4/2.1.1 or 2.2.4/2.0.10 combinations work.

**Comment by giniedp** [comment]
i am using the option `useTranspileModule`. If i set it to `false`, i get the error that is discussed in https://github.com/s-panferov/awesome-typescript-loader/issues/372 

I also found out, that if i remove `typeRoots` from my `tsconfig.json`, i dont get any of these errors. Obviously i get other build errors without typings.

**Comment by giniedp** [comment]
now #372 references the issue #320 that is about empty d.ts files. And indeed i do have an empty `index.d.ts` in my typings folder. I remember that i created it some time ago, when typescript or ATL did not compile without it for some reason (dont remember)

If i remove the empty file, i can successfully build with latest ATL version

**Comment by vincentw56** [comment]
That could be why I am not having issues now. These are my options in tsconfig:

```
  "awesomeTypescriptLoaderOptions": {
    "doTypeCheck": true,
    "forkChecker": true,
    "useBabel": true,
    "useCache": true
  }
```

**Comment by BrainCrumbz** [comment]
Just had this issue, more or less out of the blue (it wasn't there last time project was built on this dev machine), with webpack 2.2.1, ATL 3.0.8, TS 2.2.1.

In order to fix it, in the following order, we:

* added explicit dependency on watchpack 1.3.1 (see https://github.com/webpack/webpack/issues/4341)
* upgraded ATL to 3.1.2

(so, not sure yet if adding watchpack was really needed).

OT: @vincentw56 could not get a complete list of properties available for *awesomeTypescriptLoaderOptions*. I kinda remember that *forkChecker* has been recently made obsolete, with webpack 2.2.x I guess. Do you know about any reference on available options? Thanks

**Comment by kcsahoo** [comment]
In tsconfig.json, I configured the following:
 "awesomeTypescriptLoaderOptions": {
    "useWebpackText": true,
    "useTranspileModule": true,
    "doTypeCheck": true,
    "forkChecker": true
  },

Then I am able use ATL 3.2.1 and Typescript 2.2.1
No errors.

Thanks to everyone who interacted and helped.

**Comment by kcsahoo** [comment]
Only this also works:

In tsconfig.json, I configured the following:
"awesomeTypescriptLoaderOptions": {
"useWebpackText": true,
"useTranspileModule": true
},

Then I am able use ATL 3.2.1 and Typescript 2.2.2
No errors.

**Comment by trodrigues** [comment]
Same here, using only `useTranspileModule` set to true.
